### ISSUE TITLE
Fix the SwatchGenerator unit test

### ISSUE THREAD

**Issue by gary-rowe** [gary-rowe/multibit-merchant#56]
The SwatchGenerator code introduces a dependency on AWT that causes problems on the CI server.

**Comment by jim618** [comment]
If you wanted something quick you could look up whether you were in headless mode and just switch the test off. 
http://java.sun.com/developer/technicalArticles/J2SE/Desktop/headless/

**Comment by gary-rowe** [comment]
Thanks, Jim. I'll have a look at it tonight.

**Comment by gary-rowe** [comment]
A lot of the Bitcoin support code needs updating to use the 0.5 release of BitCoinJ, and the later versions of code present in MultiBit for swatch generation. To that end, I've pulled a lot of the old stuff out in preparation for an entirely new approach.
